### ISSUE TITLE
Publish to NPM 📤

### ISSUE THREAD

**Issue by geoffdavis92** [archermalmo/am.js#4]
Prepare am.js for publishing, publish to npm, test npm usage.

- [x] Confirm all `/dist` files work with intended targeted environment(s)
- [x] Confirm all tests pass
- [x] Add TravisCI (#5)
- [x] Publish to npm
- [x] Test `npm`, `yarn` installation
- [x] Test ESM use cases (node, frontend bundler)
- [x] Test CJS use cases (node, frontend bundler)
- [x] Test IIFE use case (frontend)
- [x] Test all `*.dev.js` files have sourcemap feature

**Comment by cameronbroe** [comment]
As part of the process of publishing to NPM, we should set up TravisCI instead of the prepublish hook for testing. It will take care of running tests and failing builds while simplifying the process of publishing new versions.

**Comment by geoffdavis92** [comment]
@cameronbroe good point. I already have precommit hooks setup for running tests, so probably could just use Travis in lieu of another Jest run.

Thanks!

**Comment by geoffdavis92** [comment]
TravisCI integration added, build passes: [Build #1 results](https://travis-ci.org/archermalmo/am.js/builds/342513937)

Closes #5

**Comment by geoffdavis92** [comment]
Published to npm under `@archermalmo/am.js`; all tests passed.
