### ISSUE TITLE
Set up branch protection on master

### ISSUE THREAD

**Issue by cameronbroe** [archermalmo/am.js#9]
As part of GitHub Flow, we should prevent anybody from pushing directly to master. Pull Requests should be enforced. Also, we should enforce code reviews by at least one other person before a merge is allowed into master.

@geoffdavis92 Your thoughts?

**Comment by geoffdavis92** [comment]
Way ahead of you on that! 

![Screenshot showing branch protections are setup on `master`, and code reviews are enforced](https://image.prntscr.com/image/ocRJeQk0ScuV-44uiY4qZQ.png)
